### ISSUE TITLE
'extension.sortJsonArrayAscending' not found

### ISSUE THREAD

**Issue by mbacs** [fvclaus/vsc-sort-json-array#1]
Issue Type: <b>Bug</b>

Install the extension
Open file.json
Select all
[ctrl][shift][p] (open command pallette)
enter "Sort JSON array"
click "Sort JSON array  ascending"

nothing happens and the message pops up at the bottom:
  command 'extension.sortJsonArrayAscending' not found

Extension version: 1.1.0
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18362

**Comment by fvclaus** [comment]
Thanks for reporting. The deployment was missing required dependencies, because they were listed as `devDependencies`. I fixed the error with release `1.1.1` that should already be available.
