### ISSUE TITLE
Values get modified

### ISSUE THREAD

**Issue by vytux-com** [fvclaus/vsc-sort-json-array#17]
I have the following as a sample JSON to sort
```
[
    {
        "Name": "a",
        "Base Path": "F:\\Apps\\a"
    },
    {
        "Name": "b",
        "Base Path": "F:\\Apps\\b"
    }
]
```
After running version 3.0.0 sort it get changed to this
```
[
    {
        "Name": "a",
        "Base Path": "F:\\\\Apps\\\\a"
    },
    {
        "Name": "b",
        "Base Path": "F:\\\\Apps\\\\b"
    }
]
```
It appears that the new version is double escaping the values and forgetting to un-escape them after the sort. The same behavior is seen both with built in sorts and Custom sorting scripts.

**Comment by fvclaus** [comment]
Thanks for reporting this issue. Your observation is correct: The new version is reading the text as is (`"\\"`) without unescaping it, like `JSON.parse()` would normally do. `JSON.stringify()` is used to turn the array into text again. It will escape escape the string and turn it into `"\\\\"`. I have to think about how I want to fix this issue. If this is a blocker for you, you can go back to the last version, `2.0.3`. It just tested it and it does not contain this issue: https://stackoverflow.com/questions/42626065/vs-code-rollback-extension-install-specific-extension-version

**Comment by fvclaus** [comment]
This is now part of `3.0.1`
