### ISSUE TITLE
Feature-Request: Sort .jsonl files

### ISSUE THREAD

**Issue by Whadup** [fvclaus/vsc-sort-json-array#8]
Would be great if this supported .jsonl files, where each line is a valid json object.

As a workaround, I put a comma at the end of each line and surround the whole file with [,] but that's rather annoying.

**Comment by fvclaus** [comment]
Yes, that sound reasonable. It also ruins the formatting. How did you get around that? I did not find any extension that support jsonl files.

I wrote some code that does what you describe automatically:
* Replace \n with ,
* Add [ and ]
* Then comes the normal sorting
* Stringify each element individually
* Join them together with \n

I did not find a "better" way to do that, but it works on the one file I have tried it on:

![jsonl_support](https://user-images.githubusercontent.com/2384738/77253734-79887b00-6c5c-11ea-8d26-6d639a35d33b.gif)


Currently I check for the file extension `jsonl`. Is this enough? Anything else I need to be aware of? The code can handle empty lines. Not sure if that would be even valid jsonl, but it certainly doesn't hurt to keep it.

**Comment by Whadup** [comment]
sounds perfect. Speaking of "valid", I'm not actually sure if .jsonl is a standardised format, or just something people came up with who need to write json arrays incrementally.

**Comment by Whadup** [comment]
As for the formatting part, you might even keep the old formatting if you don't sort the array, but only its indices. Then you can use the sorted indices to construct the output from the original line strings, no JSON-serialization required.

Unfortunately it's not as easy when sorting real json files, as in your other github issue...

**Comment by fvclaus** [comment]
I have build a pre-release for the 2.0.0 version that contains jsonl support [here](https://mega.nz/#!fINUHYRT!ZNReTG-4hkJAwuteJsNt5H5-SJfabKutRULQ6viVPbA). You can install it, if you go to extensions in vscode, click on the `...` on the top right and select  `Install from VSIX`. I would like to hear you feedback, before I officially release the new version.

**Comment by fvclaus** [comment]
This is now part of `2.0.0`
